// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDRs5K5q_DgNPzuAf8W6a73Ms35l5hMro',
    appId: '1:100280489861:android:195c80a8b7bdad03f7d6ec',
    messagingSenderId: '100280489861',
    projectId: 'my-test-app-flavors-dev-709d2',
    storageBucket: 'my-test-app-flavors-dev-709d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9EZrZ0b4yWhvMbxrKSTYuuGxtLvUa2eY',
    appId: '1:100280489861:ios:1e754b337e2f01b3f7d6ec',
    messagingSenderId: '100280489861',
    projectId: 'my-test-app-flavors-dev-709d2',
    storageBucket: 'my-test-app-flavors-dev-709d2.appspot.com',
    iosClientId: '100280489861-jud215n2rn540locm7ptnmp4uds251u4.apps.googleusercontent.com',
    iosBundleId: 'com.getboolean.my-test-app-flavors.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9EZrZ0b4yWhvMbxrKSTYuuGxtLvUa2eY',
    appId: '1:100280489861:ios:1e754b337e2f01b3f7d6ec',
    messagingSenderId: '100280489861',
    projectId: 'my-test-app-flavors-dev-709d2',
    storageBucket: 'my-test-app-flavors-dev-709d2.appspot.com',
    iosClientId: '100280489861-jud215n2rn540locm7ptnmp4uds251u4.apps.googleusercontent.com',
    iosBundleId: 'com.getboolean.my-test-app-flavors.dev',
  );
}
